file-version: 1
language: 'en' # Language to use for messages

settings:
  registration-timeout: 60 # Time in seconds before a non-registered player is kicked
  login-timeout: 60 # Time in seconds before a non-logged in player is kicked
  premium-bypass: true # Allow premium players to bypass authentication
  premium-command: false # Allow premium users that have signed-in to bypass authentication after executing /premium (This command is disabled if premium-bypass is enabled)

servers:
  auth_servers:
    - 'auth-1'
  lobby_servers:
    - 'lobby-1'

# MongoDB database connection
mongodb-uri: 'mongodb://localhost:27017'