language: 'en' # Language to use for messages
settings:
  password-hash: 'bcrypt' # Hashing algorithm for passwords
  registration-timeout: 60 # Time in seconds before a non-registered player is kicked
  login-timeout: 60 # Time in seconds before a non-logged in player is kicked
  premium-bypass: true # Allow premium players to bypass authentication
  premium-command: false # Allow premium users that have signed-in to bypass authentication after executing /premium (This command is disabled if premium-bypass is enabled)
