file-version: 1

settings:
  registration-timeout: 60 # Time in seconds before a non-registered player is kicked
  login-timeout: 60 # Time in seconds before a non-logged in player is kicked
  premium-bypass: true # Allow premium players to bypass authentication - If false, all players must authenticate, premiums have /premium command

servers:
  auth_servers:
    - 'auth-1'
  lobby_servers:
    - 'lobby-1'

# MongoDB database connection
mongo:
  uri: 'mongodb://localhost:27017'
  database: 'simple-auth'
